### ISSUE TITLE
zlib.h: No such file or directory

### ISSUE THREAD

**Issue by zhoudreames** [dfguan/asset#5]
I got a error when I have runned make，below this error.

gcc -g -Wall -D VERBOSE -O2 -D PRINT_COVERAGE    -c -o paf.o paf.c
paf.c:1:10: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make: *** [paf.o] Error 1

my zlib.h path is /usr/include/zlib.h，but i dont know how to fix this problem，i hope you can help me ,thank you!!

**Comment by zhoudreames** [comment]
@dfguan

**Comment by dfguan** [comment]
Hi, not sure which OS you are using, but for centos you should install
zlib-devel, for ubuntu zlib1g-dev. Best, Dengfeng.

**Comment by zhoudreames** [comment]
thanks~ solved
