### ISSUE TITLE
pchlst_final.bed Result

### ISSUE THREAD

**Issue by zhoudreames** [dfguan/asset#6]
in final line ,what`s  means of the "S" and "C" ?
![image](https://user-images.githubusercontent.com/54714639/114115809-1e343400-9916-11eb-9ea2-1a5290501ee1.png)

**Comment by zhoudreames** [comment]
@kant @dfguan  could you help me

**Comment by dfguan** [comment]
S is the the join error, which means two contig should not be joined together.  and C is the contig error, means this part of the sequence may be misassembled. Dengfeng.
